// Code generated by go-swagger; DO NOT EDIT.

package folder

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new folder API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for folder API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetFoldersGetPhp(params *GetFoldersGetPhpParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetFoldersGetPhpOK, error)

	PostFoldersAddPhp(params *PostFoldersAddPhpParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostFoldersAddPhpOK, error)

	PostFoldersDeletePhp(params *PostFoldersDeletePhpParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostFoldersDeletePhpOK, error)

	PostFoldersEditPhp(params *PostFoldersEditPhpParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostFoldersEditPhpOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetFoldersGetPhp get folders get php API
*/
func (a *Client) GetFoldersGetPhp(params *GetFoldersGetPhpParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetFoldersGetPhpOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetFoldersGetPhpParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetFoldersGetPhp",
		Method:             "GET",
		PathPattern:        "/folders/get.php",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetFoldersGetPhpReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetFoldersGetPhpOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetFoldersGetPhp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostFoldersAddPhp post folders add php API
*/
func (a *Client) PostFoldersAddPhp(params *PostFoldersAddPhpParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostFoldersAddPhpOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostFoldersAddPhpParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostFoldersAddPhp",
		Method:             "POST",
		PathPattern:        "/folders/add.php",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostFoldersAddPhpReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostFoldersAddPhpOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostFoldersAddPhp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostFoldersDeletePhp post folders delete php API
*/
func (a *Client) PostFoldersDeletePhp(params *PostFoldersDeletePhpParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostFoldersDeletePhpOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostFoldersDeletePhpParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostFoldersDeletePhp",
		Method:             "POST",
		PathPattern:        "/folders/delete.php",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostFoldersDeletePhpReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostFoldersDeletePhpOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostFoldersDeletePhp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostFoldersEditPhp post folders edit php API
*/
func (a *Client) PostFoldersEditPhp(params *PostFoldersEditPhpParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostFoldersEditPhpOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostFoldersEditPhpParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostFoldersEditPhp",
		Method:             "POST",
		PathPattern:        "/folders/edit.php",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostFoldersEditPhpReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostFoldersEditPhpOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostFoldersEditPhp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
