// Code generated by go-swagger; DO NOT EDIT.

package context

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	ccontext "context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPostContextsAddPhpParams creates a new PostContextsAddPhpParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostContextsAddPhpParams() *PostContextsAddPhpParams {
	return &PostContextsAddPhpParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostContextsAddPhpParamsWithTimeout creates a new PostContextsAddPhpParams object
// with the ability to set a timeout on a request.
func NewPostContextsAddPhpParamsWithTimeout(timeout time.Duration) *PostContextsAddPhpParams {
	return &PostContextsAddPhpParams{
		timeout: timeout,
	}
}

// NewPostContextsAddPhpParamsWithContext creates a new PostContextsAddPhpParams object
// with the ability to set a context for a request.
func NewPostContextsAddPhpParamsWithContext(ctx ccontext.Context) *PostContextsAddPhpParams {
	return &PostContextsAddPhpParams{
		Context: ctx,
	}
}

// NewPostContextsAddPhpParamsWithHTTPClient creates a new PostContextsAddPhpParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostContextsAddPhpParamsWithHTTPClient(client *http.Client) *PostContextsAddPhpParams {
	return &PostContextsAddPhpParams{
		HTTPClient: client,
	}
}

/*
PostContextsAddPhpParams contains all the parameters to send to the API endpoint

	for the post contexts add php operation.

	Typically these are written to a http.Request.
*/
type PostContextsAddPhpParams struct {

	// Name.
	Name string

	// Private.
	Private *int64

	timeout    time.Duration
	Context    ccontext.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post contexts add php params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostContextsAddPhpParams) WithDefaults() *PostContextsAddPhpParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post contexts add php params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostContextsAddPhpParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post contexts add php params
func (o *PostContextsAddPhpParams) WithTimeout(timeout time.Duration) *PostContextsAddPhpParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post contexts add php params
func (o *PostContextsAddPhpParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post contexts add php params
func (o *PostContextsAddPhpParams) WithContext(ctx ccontext.Context) *PostContextsAddPhpParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post contexts add php params
func (o *PostContextsAddPhpParams) SetContext(ctx ccontext.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post contexts add php params
func (o *PostContextsAddPhpParams) WithHTTPClient(client *http.Client) *PostContextsAddPhpParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post contexts add php params
func (o *PostContextsAddPhpParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the post contexts add php params
func (o *PostContextsAddPhpParams) WithName(name string) *PostContextsAddPhpParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the post contexts add php params
func (o *PostContextsAddPhpParams) SetName(name string) {
	o.Name = name
}

// WithPrivate adds the private to the post contexts add php params
func (o *PostContextsAddPhpParams) WithPrivate(private *int64) *PostContextsAddPhpParams {
	o.SetPrivate(private)
	return o
}

// SetPrivate adds the private to the post contexts add php params
func (o *PostContextsAddPhpParams) SetPrivate(private *int64) {
	o.Private = private
}

// WriteToRequest writes these params to a swagger request
func (o *PostContextsAddPhpParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param name
	qrName := o.Name
	qName := qrName
	if qName != "" {

		if err := r.SetQueryParam("name", qName); err != nil {
			return err
		}
	}

	if o.Private != nil {

		// query param private
		var qrPrivate int64

		if o.Private != nil {
			qrPrivate = *o.Private
		}
		qPrivate := swag.FormatInt64(qrPrivate)
		if qPrivate != "" {

			if err := r.SetQueryParam("private", qPrivate); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
