// Code generated by mockery v2.20.0. DO NOT EDIT.

package mockfetchers

import (
	fetchers "github.com/alswl/go-toodledo/pkg/common"
	mock "github.com/stretchr/testify/mock"
)

// FetchFn is an autogenerated mock type for the FetchFn type
type FetchFn struct {
	mock.Mock
}

// Execute provides a mock function with given fields: sd, isHardRefresh
func (_m *FetchFn) Execute(sd fetchers.StatusDescriber, isHardRefresh bool) error {
	ret := _m.Called(sd, isHardRefresh)

	var r0 error
	if rf, ok := ret.Get(0).(func(fetchers.StatusDescriber, bool) error); ok {
		r0 = rf(sd, isHardRefresh)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewFetchFn interface {
	mock.TestingT
	Cleanup(func())
}

// NewFetchFn creates a new instance of FetchFn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFetchFn(t mockConstructorTestingTNewFetchFn) *FetchFn {
	mock := &FetchFn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
