// Code generated by mockery v2.15.0. DO NOT EDIT.

package mockfetchers

import mock "github.com/stretchr/testify/mock"

// Progress is an autogenerated mock type for the Progress type
type Progress struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *Progress) Execute() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

type mockConstructorTestingTNewProgress interface {
	mock.TestingT
	Cleanup(func())
}

// NewProgress creates a new instance of Progress. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProgress(t mockConstructorTestingTNewProgress) *Progress {
	mock := &Progress{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
