// Code generated by mockery v2.14.0. DO NOT EDIT.

package mockfetcher

import (
	fetcher "github.com/alswl/go-toodledo/pkg/fetchers"
	mock "github.com/stretchr/testify/mock"
)

// Fetcher is an autogenerated mock type for the Fetcher type
type Fetcher struct {
	mock.Mock
}

// Execute provides a mock function with given fields: sd
func (_m *Fetcher) Execute(sd fetcher.StatusDescriber) error {
	ret := _m.Called(sd)

	var r0 error
	if rf, ok := ret.Get(0).(func(fetcher.StatusDescriber) error); ok {
		r0 = rf(sd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewFetcher interface {
	mock.TestingT
	Cleanup(func())
}

// NewFetcher creates a new instance of Fetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFetcher(t mockConstructorTestingTNewFetcher) *Fetcher {
	mock := &Fetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
