// Code generated by mockery v2.14.0. DO NOT EDIT.

package mockfetcher

import mock "github.com/stretchr/testify/mock"

// StatusDescriber is an autogenerated mock type for the StatusDescriber type
type StatusDescriber struct {
	mock.Mock
}

// Error provides a mock function with given fields:
func (_m *StatusDescriber) Error() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Message provides a mock function with given fields:
func (_m *StatusDescriber) Message() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Progress provides a mock function with given fields:
func (_m *StatusDescriber) Progress() (int, int) {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func() int); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// SetError provides a mock function with given fields: e
func (_m *StatusDescriber) SetError(e error) {
	_m.Called(e)
}

// SetMessage provides a mock function with given fields: msg
func (_m *StatusDescriber) SetMessage(msg string) {
	_m.Called(msg)
}

// SetProgress provides a mock function with given fields: current, total
func (_m *StatusDescriber) SetProgress(current int, total int) {
	_m.Called(current, total)
}

type mockConstructorTestingTNewStatusDescriber interface {
	mock.TestingT
	Cleanup(func())
}

// NewStatusDescriber creates a new instance of StatusDescriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStatusDescriber(t mockConstructorTestingTNewStatusDescriber) *StatusDescriber {
	mock := &StatusDescriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
