// Code generated by mockery v2.14.0. DO NOT EDIT.

package mockfetcher

import mock "github.com/stretchr/testify/mock"

// ToodledoFetcher is an autogenerated mock type for the ToodledoFetcher type
type ToodledoFetcher struct {
	mock.Mock
}

// FetchOnce provides a mock function with given fields:
func (_m *ToodledoFetcher) FetchOnce() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewToodledoFetcher interface {
	mock.TestingT
	Cleanup(func())
}

// NewToodledoFetcher creates a new instance of ToodledoFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewToodledoFetcher(t mockConstructorTestingTNewToodledoFetcher) *ToodledoFetcher {
	mock := &ToodledoFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
