// Code generated by "stringer -type=DueDateMode"; DO NOT EDIT.

package tasks

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DueDateModeDueBy-0]
	_ = x[DueDateModeDueOn-1]
	_ = x[DueDateModeDueAfter-2]
	_ = x[DueDateModeOptionally-3]
}

const _DueDateMode_name = "DueDateModeDueByDueDateModeDueOnDueDateModeDueAfterDueDateModeOptionally"

var _DueDateMode_index = [...]uint8{0, 16, 32, 51, 72}

func (i DueDateMode) String() string {
	if i < 0 || i >= DueDateMode(len(_DueDateMode_index)-1) {
		return "DueDateMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DueDateMode_name[_DueDateMode_index[i]:_DueDateMode_index[i+1]]
}
