// Code generated by "stringer -type=Priority"; DO NOT EDIT.

package tasks

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PriorityNegative - -1]
	_ = x[PriorityLow-0]
	_ = x[PriorityMedium-1]
	_ = x[PriorityHigh-2]
	_ = x[PriorityTop-3]
}

const _Priority_name = "PriorityNegativePriorityLowPriorityMediumPriorityHighPriorityTop"

var _Priority_index = [...]uint8{0, 16, 27, 41, 53, 64}

func (i Priority) String() string {
	i -= -1
	if i < 0 || i >= Priority(len(_Priority_index)-1) {
		return "Priority(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Priority_name[_Priority_index[i]:_Priority_index[i+1]]
}
