// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocktaskspane

import (
	mock "github.com/stretchr/testify/mock"

	tea "github.com/charmbracelet/bubbletea"
)

// parent is an autogenerated mock type for the parent type
type parent struct {
	mock.Mock
}

// Error provides a mock function with given fields: msg
func (_m *parent) Error(msg string) {
	_m.Called(msg)
}

// Info provides a mock function with given fields: msg
func (_m *parent) Info(msg string) {
	_m.Called(msg)
}

// Refresh provides a mock function with given fields: isHardRefresh
func (_m *parent) Refresh(isHardRefresh bool) tea.Cmd {
	ret := _m.Called(isHardRefresh)

	var r0 tea.Cmd
	if rf, ok := ret.Get(0).(func(bool) tea.Cmd); ok {
		r0 = rf(isHardRefresh)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tea.Cmd)
		}
	}

	return r0
}

// Warn provides a mock function with given fields: msg
func (_m *parent) Warn(msg string) {
	_m.Called(msg)
}

type mockConstructorTestingTnewParent interface {
	mock.TestingT
	Cleanup(func())
}

// newParent creates a new instance of parent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newParent(t mockConstructorTestingTnewParent) *parent {
	mock := &parent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
