// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocksyncer

import mock "github.com/stretchr/testify/mock"

// Progress is an autogenerated mock type for the Progress type
type Progress struct {
	mock.Mock
}

// Finish provides a mock function with given fields:
func (_m *Progress) Finish() {
	_m.Called()
}

// Start provides a mock function with given fields: _a0
func (_m *Progress) Start(_a0 int) {
	_m.Called(_a0)
}

// Update provides a mock function with given fields: _a0
func (_m *Progress) Update(_a0 int) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewProgress interface {
	mock.TestingT
	Cleanup(func())
}

// NewProgress creates a new instance of Progress. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProgress(t mockConstructorTestingTNewProgress) *Progress {
	mock := &Progress{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
