// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocksyncer

import (
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// Progress is an autogenerated mock type for the Progress type
type Progress struct {
	mock.Mock
}

// Finish provides a mock function with given fields:
func (_m *Progress) Finish() {
	_m.Called()
}

// Start provides a mock function with given fields: _a0
func (_m *Progress) Start(_a0 int) {
	_m.Called(_a0)
}

// Update provides a mock function with given fields: _a0
func (_m *Progress) Update(_a0 int) {
	_m.Called(_a0)
}

// NewProgress creates a new instance of Progress. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewProgress(t testing.TB) *Progress {
	mock := &Progress{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
