// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocksyncer

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// Syncer is an autogenerated mock type for the Syncer type
type Syncer struct {
	mock.Mock
}

// Start provides a mock function with given fields: _a0
func (_m *Syncer) Start(_a0 context.Context) {
	_m.Called(_a0)
}

// Stop provides a mock function with given fields:
func (_m *Syncer) Stop() {
	_m.Called()
}

// sync provides a mock function with given fields:
func (_m *Syncer) sync() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSyncer creates a new instance of Syncer. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewSyncer(t testing.TB) *Syncer {
	mock := &Syncer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
