// Code generated by "stringer -type=Status"; DO NOT EDIT.

package status

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[NextAction-1]
	_ = x[Active-2]
	_ = x[Planning-3]
	_ = x[Delegated-4]
	_ = x[Waiting-5]
	_ = x[Hold-6]
	_ = x[Postponed-7]
	_ = x[Someday-8]
	_ = x[Canceled-9]
	_ = x[Reference-10]
}

const _Status_name = "NoneNextActionActivePlanningDelegatedWaitingHoldPostponedSomedayCanceledReference"

var _Status_index = [...]uint8{0, 4, 14, 20, 28, 37, 44, 48, 57, 64, 72, 81}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
