// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	ccontext "context"
	"github.com/go-openapi/strfmt"
)

// PaginatedAPIResponse paginated Api response
//
// swagger:model PaginatedApiResponse
type PaginatedAPIResponse []interface{}

// Validate validates this paginated Api response
func (m PaginatedAPIResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this paginated Api response based on context it is used
func (m PaginatedAPIResponse) ContextValidate(ctx ccontext.Context, formats strfmt.Registry) error {
	return nil
}
