// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	ccontext "context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PaginatedInfo paginated info
//
// swagger:model PaginatedInfo
type PaginatedInfo struct {

	// num
	Num int64 `json:"num,omitempty"`

	// total
	Total int64 `json:"total,omitempty"`
}

// Validate validates this paginated info
func (m *PaginatedInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this paginated info based on context it is used
func (m *PaginatedInfo) ContextValidate(ctx ccontext.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PaginatedInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PaginatedInfo) UnmarshalBinary(b []byte) error {
	var res PaginatedInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
