// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	ccontext "context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TaskDeleted task deleted
//
// swagger:model TaskDeleted
type TaskDeleted struct {

	// The server id number for this task. It is guaranteed to be unique per account, but two different accounts may have two different tasks with the same id number.
	ID int64 `json:"id,omitempty"`

	// A GMT unix timestamp.
	Stamp int64 `json:"stamp,omitempty"`
}

// Validate validates this task deleted
func (m *TaskDeleted) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this task deleted based on context it is used
func (m *TaskDeleted) ContextValidate(ctx ccontext.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TaskDeleted) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskDeleted) UnmarshalBinary(b []byte) error {
	var res TaskDeleted
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
