// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	ccontext "context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SearchGroupItem search group item
//
// swagger:model SearchGroupItem
type SearchGroupItem struct {

	// field
	Field string `json:"field,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this search group item
func (m *SearchGroupItem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this search group item based on context it is used
func (m *SearchGroupItem) ContextValidate(ctx ccontext.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SearchGroupItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SearchGroupItem) UnmarshalBinary(b []byte) error {
	var res SearchGroupItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
