// Code generated by go-swagger; DO NOT EDIT.

package folder

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	ccontext "context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/alswl/go-toodledo/pkg/models"
)

// PostFoldersDeletePhpReader is a Reader for the PostFoldersDeletePhp structure.
type PostFoldersDeletePhpReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostFoldersDeletePhpReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostFoldersDeletePhpOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostFoldersDeletePhpUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewPostFoldersDeletePhpTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewPostFoldersDeletePhpServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostFoldersDeletePhpOK creates a PostFoldersDeletePhpOK with default headers values
func NewPostFoldersDeletePhpOK() *PostFoldersDeletePhpOK {
	return &PostFoldersDeletePhpOK{}
}

/*
PostFoldersDeletePhpOK describes a response with status code 200, with default header values.

ok
*/
type PostFoldersDeletePhpOK struct {
	Payload *PostFoldersDeletePhpOKBody
}

func (o *PostFoldersDeletePhpOK) Error() string {
	return fmt.Sprintf("[POST /folders/delete.php][%d] postFoldersDeletePhpOK  %+v", 200, o.Payload)
}
func (o *PostFoldersDeletePhpOK) GetPayload() *PostFoldersDeletePhpOKBody {
	return o.Payload
}

func (o *PostFoldersDeletePhpOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostFoldersDeletePhpOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostFoldersDeletePhpUnauthorized creates a PostFoldersDeletePhpUnauthorized with default headers values
func NewPostFoldersDeletePhpUnauthorized() *PostFoldersDeletePhpUnauthorized {
	return &PostFoldersDeletePhpUnauthorized{}
}

/*
PostFoldersDeletePhpUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostFoldersDeletePhpUnauthorized struct {
	Payload *models.Error
}

func (o *PostFoldersDeletePhpUnauthorized) Error() string {
	return fmt.Sprintf("[POST /folders/delete.php][%d] postFoldersDeletePhpUnauthorized  %+v", 401, o.Payload)
}
func (o *PostFoldersDeletePhpUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostFoldersDeletePhpUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostFoldersDeletePhpTooManyRequests creates a PostFoldersDeletePhpTooManyRequests with default headers values
func NewPostFoldersDeletePhpTooManyRequests() *PostFoldersDeletePhpTooManyRequests {
	return &PostFoldersDeletePhpTooManyRequests{}
}

/*
PostFoldersDeletePhpTooManyRequests describes a response with status code 429, with default header values.

TooManyRequests
*/
type PostFoldersDeletePhpTooManyRequests struct {
	Payload *models.Error
}

func (o *PostFoldersDeletePhpTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /folders/delete.php][%d] postFoldersDeletePhpTooManyRequests  %+v", 429, o.Payload)
}
func (o *PostFoldersDeletePhpTooManyRequests) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostFoldersDeletePhpTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostFoldersDeletePhpServiceUnavailable creates a PostFoldersDeletePhpServiceUnavailable with default headers values
func NewPostFoldersDeletePhpServiceUnavailable() *PostFoldersDeletePhpServiceUnavailable {
	return &PostFoldersDeletePhpServiceUnavailable{}
}

/*
PostFoldersDeletePhpServiceUnavailable describes a response with status code 503, with default header values.

ServiceUnavailable
*/
type PostFoldersDeletePhpServiceUnavailable struct {
	Payload *models.Error
}

func (o *PostFoldersDeletePhpServiceUnavailable) Error() string {
	return fmt.Sprintf("[POST /folders/delete.php][%d] postFoldersDeletePhpServiceUnavailable  %+v", 503, o.Payload)
}
func (o *PostFoldersDeletePhpServiceUnavailable) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostFoldersDeletePhpServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
PostFoldersDeletePhpOKBody post folders delete php o k body
swagger:model PostFoldersDeletePhpOKBody
*/
type PostFoldersDeletePhpOKBody struct {

	// deleted
	Deleted int64 `json:"deleted,omitempty"`
}

// Validate validates this post folders delete php o k body
func (o *PostFoldersDeletePhpOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post folders delete php o k body based on context it is used
func (o *PostFoldersDeletePhpOKBody) ContextValidate(ctx ccontext.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostFoldersDeletePhpOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostFoldersDeletePhpOKBody) UnmarshalBinary(b []byte) error {
	var res PostFoldersDeletePhpOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
