// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	ccontext "context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostTasksEditPhpParams creates a new PostTasksEditPhpParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostTasksEditPhpParams() *PostTasksEditPhpParams {
	return &PostTasksEditPhpParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostTasksEditPhpParamsWithTimeout creates a new PostTasksEditPhpParams object
// with the ability to set a timeout on a request.
func NewPostTasksEditPhpParamsWithTimeout(timeout time.Duration) *PostTasksEditPhpParams {
	return &PostTasksEditPhpParams{
		timeout: timeout,
	}
}

// NewPostTasksEditPhpParamsWithContext creates a new PostTasksEditPhpParams object
// with the ability to set a context for a request.
func NewPostTasksEditPhpParamsWithContext(ctx ccontext.Context) *PostTasksEditPhpParams {
	return &PostTasksEditPhpParams{
		Context: ctx,
	}
}

// NewPostTasksEditPhpParamsWithHTTPClient creates a new PostTasksEditPhpParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostTasksEditPhpParamsWithHTTPClient(client *http.Client) *PostTasksEditPhpParams {
	return &PostTasksEditPhpParams{
		HTTPClient: client,
	}
}

/*
PostTasksEditPhpParams contains all the parameters to send to the API endpoint

	for the post tasks edit php operation.

	Typically these are written to a http.Request.
*/
type PostTasksEditPhpParams struct {

	/* Fields.

	   A comma separated list of optional fields that you want returned. For efficiency, you should omit fields that you don't use. This will make downloading, parsing and syncing go much faster.
	*/
	Fields *string

	/* Tasks.

	   Array of tasks, should be put json string, id is required reschedule field is optional, set to "1" if you want Toodledo to automatically reschedule the repeating task for you.
	*/
	Tasks *string

	timeout    time.Duration
	Context    ccontext.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post tasks edit php params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostTasksEditPhpParams) WithDefaults() *PostTasksEditPhpParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post tasks edit php params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostTasksEditPhpParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post tasks edit php params
func (o *PostTasksEditPhpParams) WithTimeout(timeout time.Duration) *PostTasksEditPhpParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post tasks edit php params
func (o *PostTasksEditPhpParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post tasks edit php params
func (o *PostTasksEditPhpParams) WithContext(ctx ccontext.Context) *PostTasksEditPhpParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post tasks edit php params
func (o *PostTasksEditPhpParams) SetContext(ctx ccontext.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post tasks edit php params
func (o *PostTasksEditPhpParams) WithHTTPClient(client *http.Client) *PostTasksEditPhpParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post tasks edit php params
func (o *PostTasksEditPhpParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the post tasks edit php params
func (o *PostTasksEditPhpParams) WithFields(fields *string) *PostTasksEditPhpParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the post tasks edit php params
func (o *PostTasksEditPhpParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithTasks adds the tasks to the post tasks edit php params
func (o *PostTasksEditPhpParams) WithTasks(tasks *string) *PostTasksEditPhpParams {
	o.SetTasks(tasks)
	return o
}

// SetTasks adds the tasks to the post tasks edit php params
func (o *PostTasksEditPhpParams) SetTasks(tasks *string) {
	o.Tasks = tasks
}

// WriteToRequest writes these params to a swagger request
func (o *PostTasksEditPhpParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	if o.Tasks != nil {

		// query param tasks
		var qrTasks string

		if o.Tasks != nil {
			qrTasks = *o.Tasks
		}
		qTasks := qrTasks
		if qTasks != "" {

			if err := r.SetQueryParam("tasks", qTasks); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
