// Code generated by mockery 2.9.0. DO NOT EDIT.

package mockservices

import (
	models "github.com/alswl/go-toodledo/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// FolderService is an autogenerated mock type for the FolderService type
type FolderService struct {
	mock.Mock
}

// FindByName provides a mock function with given fields: name
func (_m *FolderService) FindByName(name string) (*models.Folder, error) {
	ret := _m.Called(name)

	var r0 *models.Folder
	if rf, ok := ret.Get(0).(func(string) *models.Folder); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Folder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
