// Code generated by mockery v2.14.1. DO NOT EDIT.

package mockservices

import (
	models "github.com/alswl/go-toodledo/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// FolderService is an autogenerated mock type for the FolderService type
type FolderService struct {
	mock.Mock
}

// Archive provides a mock function with given fields: id, isArchived
func (_m *FolderService) Archive(id int, isArchived bool) (*models.Folder, error) {
	ret := _m.Called(id, isArchived)

	var r0 *models.Folder
	if rf, ok := ret.Get(0).(func(int, bool) *models.Folder); ok {
		r0 = rf(id, isArchived)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Folder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, bool) error); ok {
		r1 = rf(id, isArchived)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: name
func (_m *FolderService) Create(name string) (*models.Folder, error) {
	ret := _m.Called(name)

	var r0 *models.Folder
	if rf, ok := ret.Get(0).(func(string) *models.Folder); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Folder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: name
func (_m *FolderService) Delete(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: name
func (_m *FolderService) Find(name string) (*models.Folder, error) {
	ret := _m.Called(name)

	var r0 *models.Folder
	if rf, ok := ret.Get(0).(func(string) *models.Folder); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Folder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: id
func (_m *FolderService) FindByID(id int64) (*models.Folder, error) {
	ret := _m.Called(id)

	var r0 *models.Folder
	if rf, ok := ret.Get(0).(func(int64) *models.Folder); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Folder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAll provides a mock function with given fields:
func (_m *FolderService) ListAll() ([]*models.Folder, error) {
	ret := _m.Called()

	var r0 []*models.Folder
	if rf, ok := ret.Get(0).(func() []*models.Folder); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Folder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Rename provides a mock function with given fields: name, newName
func (_m *FolderService) Rename(name string, newName string) (*models.Folder, error) {
	ret := _m.Called(name, newName)

	var r0 *models.Folder
	if rf, ok := ret.Get(0).(func(string, string) *models.Folder); ok {
		r0 = rf(name, newName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Folder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(name, newName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewFolderService interface {
	mock.TestingT
	Cleanup(func())
}

// NewFolderService creates a new instance of FolderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFolderService(t mockConstructorTestingTNewFolderService) *FolderService {
	mock := &FolderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
