// Code generated by mockery v2.9.4. DO NOT EDIT.

package mockservices

import (
	models "github.com/alswl/go-toodledo/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// FolderCachedService is an autogenerated mock type for the FolderCachedService type
type FolderCachedService struct {
	mock.Mock
}

// Archive provides a mock function with given fields: id, isArchived
func (_m *FolderCachedService) Archive(id int, isArchived bool) (*models.Folder, error) {
	ret := _m.Called(id, isArchived)

	var r0 *models.Folder
	if rf, ok := ret.Get(0).(func(int, bool) *models.Folder); ok {
		r0 = rf(id, isArchived)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Folder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, bool) error); ok {
		r1 = rf(id, isArchived)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: name
func (_m *FolderCachedService) Create(name string) (*models.Folder, error) {
	ret := _m.Called(name)

	var r0 *models.Folder
	if rf, ok := ret.Get(0).(func(string) *models.Folder); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Folder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: name
func (_m *FolderCachedService) Delete(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: name
func (_m *FolderCachedService) Find(name string) (*models.Folder, error) {
	ret := _m.Called(name)

	var r0 *models.Folder
	if rf, ok := ret.Get(0).(func(string) *models.Folder); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Folder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAll provides a mock function with given fields:
func (_m *FolderCachedService) ListAll() ([]*models.Folder, error) {
	ret := _m.Called()

	var r0 []*models.Folder
	if rf, ok := ret.Get(0).(func() []*models.Folder); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Folder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LocalClear provides a mock function with given fields:
func (_m *FolderCachedService) LocalClear() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Rename provides a mock function with given fields: name, newName
func (_m *FolderCachedService) Rename(name string, newName string) (*models.Folder, error) {
	ret := _m.Called(name, newName)

	var r0 *models.Folder
	if rf, ok := ret.Get(0).(func(string, string) *models.Folder); ok {
		r0 = rf(name, newName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Folder)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(name, newName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Sync provides a mock function with given fields:
func (_m *FolderCachedService) Sync() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
