// Code generated by "stringer -type Priority"; DO NOT EDIT.

package priority

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Negative - -1]
	_ = x[Low-0]
	_ = x[Medium-1]
	_ = x[High-2]
	_ = x[Top-3]
}

const _Priority_name = "NegativeLowMediumHighTop"

var _Priority_index = [...]uint8{0, 8, 11, 17, 21, 24}

func (i Priority) String() string {
	i -= -1
	if i < 0 || i >= Priority(len(_Priority_index)-1) {
		return "Priority(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Priority_name[_Priority_index[i]:_Priority_index[i+1]]
}
