// Code generated by go-swagger; DO NOT EDIT.

package goal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/alswl/go-toodledo/pkg/models"
)

// PostGoalsDeletePhpReader is a Reader for the PostGoalsDeletePhp structure.
type PostGoalsDeletePhpReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostGoalsDeletePhpReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostGoalsDeletePhpOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostGoalsDeletePhpUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewPostGoalsDeletePhpTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewPostGoalsDeletePhpServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostGoalsDeletePhpOK creates a PostGoalsDeletePhpOK with default headers values
func NewPostGoalsDeletePhpOK() *PostGoalsDeletePhpOK {
	return &PostGoalsDeletePhpOK{}
}

/* PostGoalsDeletePhpOK describes a response with status code 200, with default header values.

ok
*/
type PostGoalsDeletePhpOK struct {
	Payload *PostGoalsDeletePhpOKBody
}

func (o *PostGoalsDeletePhpOK) Error() string {
	return fmt.Sprintf("[POST /goals/delete.php][%d] postGoalsDeletePhpOK  %+v", 200, o.Payload)
}
func (o *PostGoalsDeletePhpOK) GetPayload() *PostGoalsDeletePhpOKBody {
	return o.Payload
}

func (o *PostGoalsDeletePhpOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostGoalsDeletePhpOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostGoalsDeletePhpUnauthorized creates a PostGoalsDeletePhpUnauthorized with default headers values
func NewPostGoalsDeletePhpUnauthorized() *PostGoalsDeletePhpUnauthorized {
	return &PostGoalsDeletePhpUnauthorized{}
}

/* PostGoalsDeletePhpUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostGoalsDeletePhpUnauthorized struct {
	Payload *models.Error
}

func (o *PostGoalsDeletePhpUnauthorized) Error() string {
	return fmt.Sprintf("[POST /goals/delete.php][%d] postGoalsDeletePhpUnauthorized  %+v", 401, o.Payload)
}
func (o *PostGoalsDeletePhpUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostGoalsDeletePhpUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostGoalsDeletePhpTooManyRequests creates a PostGoalsDeletePhpTooManyRequests with default headers values
func NewPostGoalsDeletePhpTooManyRequests() *PostGoalsDeletePhpTooManyRequests {
	return &PostGoalsDeletePhpTooManyRequests{}
}

/* PostGoalsDeletePhpTooManyRequests describes a response with status code 429, with default header values.

TooManyRequests
*/
type PostGoalsDeletePhpTooManyRequests struct {
	Payload *models.Error
}

func (o *PostGoalsDeletePhpTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /goals/delete.php][%d] postGoalsDeletePhpTooManyRequests  %+v", 429, o.Payload)
}
func (o *PostGoalsDeletePhpTooManyRequests) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostGoalsDeletePhpTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostGoalsDeletePhpServiceUnavailable creates a PostGoalsDeletePhpServiceUnavailable with default headers values
func NewPostGoalsDeletePhpServiceUnavailable() *PostGoalsDeletePhpServiceUnavailable {
	return &PostGoalsDeletePhpServiceUnavailable{}
}

/* PostGoalsDeletePhpServiceUnavailable describes a response with status code 503, with default header values.

ServiceUnavailable
*/
type PostGoalsDeletePhpServiceUnavailable struct {
	Payload *models.Error
}

func (o *PostGoalsDeletePhpServiceUnavailable) Error() string {
	return fmt.Sprintf("[POST /goals/delete.php][%d] postGoalsDeletePhpServiceUnavailable  %+v", 503, o.Payload)
}
func (o *PostGoalsDeletePhpServiceUnavailable) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostGoalsDeletePhpServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostGoalsDeletePhpOKBody post goals delete php o k body
swagger:model PostGoalsDeletePhpOKBody
*/
type PostGoalsDeletePhpOKBody struct {

	// deleted
	Deleted int64 `json:"deleted,omitempty"`
}

// Validate validates this post goals delete php o k body
func (o *PostGoalsDeletePhpOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post goals delete php o k body based on context it is used
func (o *PostGoalsDeletePhpOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostGoalsDeletePhpOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostGoalsDeletePhpOKBody) UnmarshalBinary(b []byte) error {
	var res PostGoalsDeletePhpOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
