// Code generated by go-swagger; DO NOT EDIT.

package goal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	ccontext "context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGoalsGetPhpParams creates a new GetGoalsGetPhpParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetGoalsGetPhpParams() *GetGoalsGetPhpParams {
	return &GetGoalsGetPhpParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetGoalsGetPhpParamsWithTimeout creates a new GetGoalsGetPhpParams object
// with the ability to set a timeout on a request.
func NewGetGoalsGetPhpParamsWithTimeout(timeout time.Duration) *GetGoalsGetPhpParams {
	return &GetGoalsGetPhpParams{
		timeout: timeout,
	}
}

// NewGetGoalsGetPhpParamsWithContext creates a new GetGoalsGetPhpParams object
// with the ability to set a context for a request.
func NewGetGoalsGetPhpParamsWithContext(ctx ccontext.Context) *GetGoalsGetPhpParams {
	return &GetGoalsGetPhpParams{
		Context: ctx,
	}
}

// NewGetGoalsGetPhpParamsWithHTTPClient creates a new GetGoalsGetPhpParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetGoalsGetPhpParamsWithHTTPClient(client *http.Client) *GetGoalsGetPhpParams {
	return &GetGoalsGetPhpParams{
		HTTPClient: client,
	}
}

/*
GetGoalsGetPhpParams contains all the parameters to send to the API endpoint

	for the get goals get php operation.

	Typically these are written to a http.Request.
*/
type GetGoalsGetPhpParams struct {
	timeout    time.Duration
	Context    ccontext.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get goals get php params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGoalsGetPhpParams) WithDefaults() *GetGoalsGetPhpParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get goals get php params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGoalsGetPhpParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get goals get php params
func (o *GetGoalsGetPhpParams) WithTimeout(timeout time.Duration) *GetGoalsGetPhpParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get goals get php params
func (o *GetGoalsGetPhpParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get goals get php params
func (o *GetGoalsGetPhpParams) WithContext(ctx ccontext.Context) *GetGoalsGetPhpParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get goals get php params
func (o *GetGoalsGetPhpParams) SetContext(ctx ccontext.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get goals get php params
func (o *GetGoalsGetPhpParams) WithHTTPClient(client *http.Client) *GetGoalsGetPhpParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get goals get php params
func (o *GetGoalsGetPhpParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetGoalsGetPhpParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
