// Code generated by go-swagger; DO NOT EDIT.

package goal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	ccontext "context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPostGoalsDeletePhpParams creates a new PostGoalsDeletePhpParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostGoalsDeletePhpParams() *PostGoalsDeletePhpParams {
	return &PostGoalsDeletePhpParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostGoalsDeletePhpParamsWithTimeout creates a new PostGoalsDeletePhpParams object
// with the ability to set a timeout on a request.
func NewPostGoalsDeletePhpParamsWithTimeout(timeout time.Duration) *PostGoalsDeletePhpParams {
	return &PostGoalsDeletePhpParams{
		timeout: timeout,
	}
}

// NewPostGoalsDeletePhpParamsWithContext creates a new PostGoalsDeletePhpParams object
// with the ability to set a context for a request.
func NewPostGoalsDeletePhpParamsWithContext(ctx ccontext.Context) *PostGoalsDeletePhpParams {
	return &PostGoalsDeletePhpParams{
		Context: ctx,
	}
}

// NewPostGoalsDeletePhpParamsWithHTTPClient creates a new PostGoalsDeletePhpParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostGoalsDeletePhpParamsWithHTTPClient(client *http.Client) *PostGoalsDeletePhpParams {
	return &PostGoalsDeletePhpParams{
		HTTPClient: client,
	}
}

/*
PostGoalsDeletePhpParams contains all the parameters to send to the API endpoint

	for the post goals delete php operation.

	Typically these are written to a http.Request.
*/
type PostGoalsDeletePhpParams struct {

	// ID.
	ID int64

	timeout    time.Duration
	Context    ccontext.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post goals delete php params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostGoalsDeletePhpParams) WithDefaults() *PostGoalsDeletePhpParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post goals delete php params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostGoalsDeletePhpParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post goals delete php params
func (o *PostGoalsDeletePhpParams) WithTimeout(timeout time.Duration) *PostGoalsDeletePhpParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post goals delete php params
func (o *PostGoalsDeletePhpParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post goals delete php params
func (o *PostGoalsDeletePhpParams) WithContext(ctx ccontext.Context) *PostGoalsDeletePhpParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post goals delete php params
func (o *PostGoalsDeletePhpParams) SetContext(ctx ccontext.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post goals delete php params
func (o *PostGoalsDeletePhpParams) WithHTTPClient(client *http.Client) *PostGoalsDeletePhpParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post goals delete php params
func (o *PostGoalsDeletePhpParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the post goals delete php params
func (o *PostGoalsDeletePhpParams) WithID(id int64) *PostGoalsDeletePhpParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post goals delete php params
func (o *PostGoalsDeletePhpParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostGoalsDeletePhpParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param id
	qrID := o.ID
	qID := swag.FormatInt64(qrID)
	if qID != "" {

		if err := r.SetQueryParam("id", qID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
