// Code generated by go-swagger; DO NOT EDIT.

package goal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	ccontext "context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPostGoalsAddPhpParams creates a new PostGoalsAddPhpParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostGoalsAddPhpParams() *PostGoalsAddPhpParams {
	return &PostGoalsAddPhpParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostGoalsAddPhpParamsWithTimeout creates a new PostGoalsAddPhpParams object
// with the ability to set a timeout on a request.
func NewPostGoalsAddPhpParamsWithTimeout(timeout time.Duration) *PostGoalsAddPhpParams {
	return &PostGoalsAddPhpParams{
		timeout: timeout,
	}
}

// NewPostGoalsAddPhpParamsWithContext creates a new PostGoalsAddPhpParams object
// with the ability to set a context for a request.
func NewPostGoalsAddPhpParamsWithContext(ctx ccontext.Context) *PostGoalsAddPhpParams {
	return &PostGoalsAddPhpParams{
		Context: ctx,
	}
}

// NewPostGoalsAddPhpParamsWithHTTPClient creates a new PostGoalsAddPhpParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostGoalsAddPhpParamsWithHTTPClient(client *http.Client) *PostGoalsAddPhpParams {
	return &PostGoalsAddPhpParams{
		HTTPClient: client,
	}
}

/*
PostGoalsAddPhpParams contains all the parameters to send to the API endpoint

	for the post goals add php operation.

	Typically these are written to a http.Request.
*/
type PostGoalsAddPhpParams struct {

	// Contributes.
	Contributes *int64

	// Level.
	Level *int64

	// Name.
	Name string

	// Note.
	Note *string

	// Private.
	Private *int64

	timeout    time.Duration
	Context    ccontext.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post goals add php params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostGoalsAddPhpParams) WithDefaults() *PostGoalsAddPhpParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post goals add php params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostGoalsAddPhpParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post goals add php params
func (o *PostGoalsAddPhpParams) WithTimeout(timeout time.Duration) *PostGoalsAddPhpParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post goals add php params
func (o *PostGoalsAddPhpParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post goals add php params
func (o *PostGoalsAddPhpParams) WithContext(ctx ccontext.Context) *PostGoalsAddPhpParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post goals add php params
func (o *PostGoalsAddPhpParams) SetContext(ctx ccontext.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post goals add php params
func (o *PostGoalsAddPhpParams) WithHTTPClient(client *http.Client) *PostGoalsAddPhpParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post goals add php params
func (o *PostGoalsAddPhpParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContributes adds the contributes to the post goals add php params
func (o *PostGoalsAddPhpParams) WithContributes(contributes *int64) *PostGoalsAddPhpParams {
	o.SetContributes(contributes)
	return o
}

// SetContributes adds the contributes to the post goals add php params
func (o *PostGoalsAddPhpParams) SetContributes(contributes *int64) {
	o.Contributes = contributes
}

// WithLevel adds the level to the post goals add php params
func (o *PostGoalsAddPhpParams) WithLevel(level *int64) *PostGoalsAddPhpParams {
	o.SetLevel(level)
	return o
}

// SetLevel adds the level to the post goals add php params
func (o *PostGoalsAddPhpParams) SetLevel(level *int64) {
	o.Level = level
}

// WithName adds the name to the post goals add php params
func (o *PostGoalsAddPhpParams) WithName(name string) *PostGoalsAddPhpParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the post goals add php params
func (o *PostGoalsAddPhpParams) SetName(name string) {
	o.Name = name
}

// WithNote adds the note to the post goals add php params
func (o *PostGoalsAddPhpParams) WithNote(note *string) *PostGoalsAddPhpParams {
	o.SetNote(note)
	return o
}

// SetNote adds the note to the post goals add php params
func (o *PostGoalsAddPhpParams) SetNote(note *string) {
	o.Note = note
}

// WithPrivate adds the private to the post goals add php params
func (o *PostGoalsAddPhpParams) WithPrivate(private *int64) *PostGoalsAddPhpParams {
	o.SetPrivate(private)
	return o
}

// SetPrivate adds the private to the post goals add php params
func (o *PostGoalsAddPhpParams) SetPrivate(private *int64) {
	o.Private = private
}

// WriteToRequest writes these params to a swagger request
func (o *PostGoalsAddPhpParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Contributes != nil {

		// query param contributes
		var qrContributes int64

		if o.Contributes != nil {
			qrContributes = *o.Contributes
		}
		qContributes := swag.FormatInt64(qrContributes)
		if qContributes != "" {

			if err := r.SetQueryParam("contributes", qContributes); err != nil {
				return err
			}
		}
	}

	if o.Level != nil {

		// query param level
		var qrLevel int64

		if o.Level != nil {
			qrLevel = *o.Level
		}
		qLevel := swag.FormatInt64(qrLevel)
		if qLevel != "" {

			if err := r.SetQueryParam("level", qLevel); err != nil {
				return err
			}
		}
	}

	// query param name
	qrName := o.Name
	qName := qrName
	if qName != "" {

		if err := r.SetQueryParam("name", qName); err != nil {
			return err
		}
	}

	if o.Note != nil {

		// query param note
		var qrNote string

		if o.Note != nil {
			qrNote = *o.Note
		}
		qNote := qrNote
		if qNote != "" {

			if err := r.SetQueryParam("note", qNote); err != nil {
				return err
			}
		}
	}

	if o.Private != nil {

		// query param private
		var qrPrivate int64

		if o.Private != nil {
			qrPrivate = *o.Private
		}
		qPrivate := swag.FormatInt64(qrPrivate)
		if qPrivate != "" {

			if err := r.SetQueryParam("private", qPrivate); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
