// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocktoodledo

import (
	context "context"

	models "github.com/alswl/go-toodledo/pkg/toodledo/models"
	mock "github.com/stretchr/testify/mock"

	toodledo "github.com/alswl/go-toodledo/pkg/toodledo"
)

// NoteService is an autogenerated mock type for the NoteService type
type NoteService struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx
func (_m *NoteService) Add(ctx context.Context) (models.Note, toodledo.Response, error) {
	ret := _m.Called(ctx)

	var r0 models.Note
	if rf, ok := ret.Get(0).(func(context.Context) models.Note); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(models.Note)
	}

	var r1 toodledo.Response
	if rf, ok := ret.Get(1).(func(context.Context) toodledo.Response); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(toodledo.Response)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Delete provides a mock function with given fields: ctx
func (_m *NoteService) Delete(ctx context.Context) (toodledo.Response, error) {
	ret := _m.Called(ctx)

	var r0 toodledo.Response
	if rf, ok := ret.Get(0).(func(context.Context) toodledo.Response); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(toodledo.Response)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Edit provides a mock function with given fields: ctx
func (_m *NoteService) Edit(ctx context.Context) (models.Note, toodledo.Response, error) {
	ret := _m.Called(ctx)

	var r0 models.Note
	if rf, ok := ret.Get(0).(func(context.Context) models.Note); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(models.Note)
	}

	var r1 toodledo.Response
	if rf, ok := ret.Get(1).(func(context.Context) toodledo.Response); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(toodledo.Response)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Get provides a mock function with given fields: ctx
func (_m *NoteService) Get(ctx context.Context) ([]models.Note, toodledo.Response, error) {
	ret := _m.Called(ctx)

	var r0 []models.Note
	if rf, ok := ret.Get(0).(func(context.Context) []models.Note); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Note)
		}
	}

	var r1 toodledo.Response
	if rf, ok := ret.Get(1).(func(context.Context) toodledo.Response); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(toodledo.Response)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
