// Code generated by "stringer -type=TaskPriority"; DO NOT EDIT.

package taskpriorities

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Negative - -1]
	_ = x[Low-0]
	_ = x[Medium-1]
	_ = x[High-2]
	_ = x[Top-3]
}

const _TaskPriority_name = "NegativeLowMediumHighTop"

var _TaskPriority_index = [...]uint8{0, 8, 11, 17, 21, 24}

func (i TaskPriority) String() string {
	i -= -1
	if i < 0 || i >= TaskPriority(len(_TaskPriority_index)-1) {
		return "TaskPriority(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _TaskPriority_name[_TaskPriority_index[i]:_TaskPriority_index[i+1]]
}
