// Code generated by mockery 2.9.0. DO NOT EDIT.

package mockcommon

import (
	models "github.com/alswl/go-toodledo/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// Configs is an autogenerated mock type for the Configs type
type Configs struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *Configs) Get() *models.ToodledoConfig {
	ret := _m.Called()

	var r0 *models.ToodledoConfig
	if rf, ok := ret.Get(0).(func() *models.ToodledoConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ToodledoConfig)
		}
	}

	return r0
}
