// Code generated by mockery v2.9.4. DO NOT EDIT.

package mockcommon

import (
	"github.com/alswl/go-toodledo/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// Configs is an autogenerated mock type for the Configs type
type Configs struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *Configs) Get() *models.ToodledoCliConfig {
	ret := _m.Called()

	var r0 *models.ToodledoCliConfig
	if rf, ok := ret.Get(0).(func() *models.ToodledoCliConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ToodledoCliConfig)
		}
	}

	return r0
}
