// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new task API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for task API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetTasksGetPhp(params *GetTasksGetPhpParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetTasksGetPhpOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetTasksGetPhp get tasks get php API
*/
func (a *Client) GetTasksGetPhp(params *GetTasksGetPhpParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetTasksGetPhpOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetTasksGetPhpParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetTasksGetPhp",
		Method:             "GET",
		PathPattern:        "/tasks/get.php",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetTasksGetPhpReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetTasksGetPhpOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetTasksGetPhp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
