// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	ccontext "context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTasksSearchPhpParams creates a new GetTasksSearchPhpParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTasksSearchPhpParams() *GetTasksSearchPhpParams {
	return &GetTasksSearchPhpParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTasksSearchPhpParamsWithTimeout creates a new GetTasksSearchPhpParams object
// with the ability to set a timeout on a request.
func NewGetTasksSearchPhpParamsWithTimeout(timeout time.Duration) *GetTasksSearchPhpParams {
	return &GetTasksSearchPhpParams{
		timeout: timeout,
	}
}

// NewGetTasksSearchPhpParamsWithContext creates a new GetTasksSearchPhpParams object
// with the ability to set a context for a request.
func NewGetTasksSearchPhpParamsWithContext(ctx ccontext.Context) *GetTasksSearchPhpParams {
	return &GetTasksSearchPhpParams{
		Context: ctx,
	}
}

// NewGetTasksSearchPhpParamsWithHTTPClient creates a new GetTasksSearchPhpParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTasksSearchPhpParamsWithHTTPClient(client *http.Client) *GetTasksSearchPhpParams {
	return &GetTasksSearchPhpParams{
		HTTPClient: client,
	}
}

/* GetTasksSearchPhpParams contains all the parameters to send to the API endpoint
   for the get tasks search php operation.

   Typically these are written to a http.Request.
*/
type GetTasksSearchPhpParams struct {
	timeout    time.Duration
	Context    ccontext.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get tasks search php params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTasksSearchPhpParams) WithDefaults() *GetTasksSearchPhpParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get tasks search php params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTasksSearchPhpParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get tasks search php params
func (o *GetTasksSearchPhpParams) WithTimeout(timeout time.Duration) *GetTasksSearchPhpParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tasks search php params
func (o *GetTasksSearchPhpParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tasks search php params
func (o *GetTasksSearchPhpParams) WithContext(ctx ccontext.Context) *GetTasksSearchPhpParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tasks search php params
func (o *GetTasksSearchPhpParams) SetContext(ctx ccontext.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tasks search php params
func (o *GetTasksSearchPhpParams) WithHTTPClient(client *http.Client) *GetTasksSearchPhpParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tasks search php params
func (o *GetTasksSearchPhpParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetTasksSearchPhpParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
