// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/alswl/go-toodledo/pkg/models"
)

// PostTasksEditPhpReader is a Reader for the PostTasksEditPhp structure.
type PostTasksEditPhpReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostTasksEditPhpReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostTasksEditPhpOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostTasksEditPhpUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewPostTasksEditPhpTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewPostTasksEditPhpServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostTasksEditPhpOK creates a PostTasksEditPhpOK with default headers values
func NewPostTasksEditPhpOK() *PostTasksEditPhpOK {
	return &PostTasksEditPhpOK{}
}

/*
	PostTasksEditPhpOK describes a response with status code 200, with default header values.

ok
*/
type PostTasksEditPhpOK struct {
	Payload []*models.Task
}

func (o *PostTasksEditPhpOK) Error() string {
	return fmt.Sprintf("[POST /tasks/edit.php][%d] postTasksEditPhpOK  %+v", 200, o.Payload)
}
func (o *PostTasksEditPhpOK) GetPayload() []*models.Task {
	return o.Payload
}

func (o *PostTasksEditPhpOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostTasksEditPhpUnauthorized creates a PostTasksEditPhpUnauthorized with default headers values
func NewPostTasksEditPhpUnauthorized() *PostTasksEditPhpUnauthorized {
	return &PostTasksEditPhpUnauthorized{}
}

/*
	PostTasksEditPhpUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostTasksEditPhpUnauthorized struct {
	Payload *models.Error
}

func (o *PostTasksEditPhpUnauthorized) Error() string {
	return fmt.Sprintf("[POST /tasks/edit.php][%d] postTasksEditPhpUnauthorized  %+v", 401, o.Payload)
}
func (o *PostTasksEditPhpUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostTasksEditPhpUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostTasksEditPhpTooManyRequests creates a PostTasksEditPhpTooManyRequests with default headers values
func NewPostTasksEditPhpTooManyRequests() *PostTasksEditPhpTooManyRequests {
	return &PostTasksEditPhpTooManyRequests{}
}

/*
	PostTasksEditPhpTooManyRequests describes a response with status code 429, with default header values.

TooManyRequests
*/
type PostTasksEditPhpTooManyRequests struct {
	Payload *models.Error
}

func (o *PostTasksEditPhpTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /tasks/edit.php][%d] postTasksEditPhpTooManyRequests  %+v", 429, o.Payload)
}
func (o *PostTasksEditPhpTooManyRequests) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostTasksEditPhpTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostTasksEditPhpServiceUnavailable creates a PostTasksEditPhpServiceUnavailable with default headers values
func NewPostTasksEditPhpServiceUnavailable() *PostTasksEditPhpServiceUnavailable {
	return &PostTasksEditPhpServiceUnavailable{}
}

/*
	PostTasksEditPhpServiceUnavailable describes a response with status code 503, with default header values.

ServiceUnavailable
*/
type PostTasksEditPhpServiceUnavailable struct {
	Payload *models.Error
}

func (o *PostTasksEditPhpServiceUnavailable) Error() string {
	return fmt.Sprintf("[POST /tasks/edit.php][%d] postTasksEditPhpServiceUnavailable  %+v", 503, o.Payload)
}
func (o *PostTasksEditPhpServiceUnavailable) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostTasksEditPhpServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
