// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	ccontext "context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostTasksAddPhpParams creates a new PostTasksAddPhpParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostTasksAddPhpParams() *PostTasksAddPhpParams {
	return &PostTasksAddPhpParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostTasksAddPhpParamsWithTimeout creates a new PostTasksAddPhpParams object
// with the ability to set a timeout on a request.
func NewPostTasksAddPhpParamsWithTimeout(timeout time.Duration) *PostTasksAddPhpParams {
	return &PostTasksAddPhpParams{
		timeout: timeout,
	}
}

// NewPostTasksAddPhpParamsWithContext creates a new PostTasksAddPhpParams object
// with the ability to set a context for a request.
func NewPostTasksAddPhpParamsWithContext(ctx ccontext.Context) *PostTasksAddPhpParams {
	return &PostTasksAddPhpParams{
		Context: ctx,
	}
}

// NewPostTasksAddPhpParamsWithHTTPClient creates a new PostTasksAddPhpParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostTasksAddPhpParamsWithHTTPClient(client *http.Client) *PostTasksAddPhpParams {
	return &PostTasksAddPhpParams{
		HTTPClient: client,
	}
}

/* PostTasksAddPhpParams contains all the parameters to send to the API endpoint
   for the post tasks add php operation.

   Typically these are written to a http.Request.
*/
type PostTasksAddPhpParams struct {

	/* Fields.

	   A comma separated list of optional fields that you want returned. For efficiency, you should omit fields that you don't use. This will make downloading, parsing and syncing go much faster.
	*/
	Fields *string

	/* Tasks.

	   Array of tasks, should be put json string
	*/
	Tasks *string

	timeout    time.Duration
	Context    ccontext.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post tasks add php params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostTasksAddPhpParams) WithDefaults() *PostTasksAddPhpParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post tasks add php params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostTasksAddPhpParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post tasks add php params
func (o *PostTasksAddPhpParams) WithTimeout(timeout time.Duration) *PostTasksAddPhpParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post tasks add php params
func (o *PostTasksAddPhpParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post tasks add php params
func (o *PostTasksAddPhpParams) WithContext(ctx ccontext.Context) *PostTasksAddPhpParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post tasks add php params
func (o *PostTasksAddPhpParams) SetContext(ctx ccontext.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post tasks add php params
func (o *PostTasksAddPhpParams) WithHTTPClient(client *http.Client) *PostTasksAddPhpParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post tasks add php params
func (o *PostTasksAddPhpParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the post tasks add php params
func (o *PostTasksAddPhpParams) WithFields(fields *string) *PostTasksAddPhpParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the post tasks add php params
func (o *PostTasksAddPhpParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithTasks adds the tasks to the post tasks add php params
func (o *PostTasksAddPhpParams) WithTasks(tasks *string) *PostTasksAddPhpParams {
	o.SetTasks(tasks)
	return o
}

// SetTasks adds the tasks to the post tasks add php params
func (o *PostTasksAddPhpParams) SetTasks(tasks *string) {
	o.Tasks = tasks
}

// WriteToRequest writes these params to a swagger request
func (o *PostTasksAddPhpParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string

		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {

			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}
	}

	if o.Tasks != nil {

		// query param tasks
		var qrTasks string

		if o.Tasks != nil {
			qrTasks = *o.Tasks
		}
		qTasks := qrTasks
		if qTasks != "" {

			if err := r.SetQueryParam("tasks", qTasks); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
