name: Go

on:
  push:
    branches: [ master, develop, fix/*, feat/* ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: "1.22"

    - name: Get dependencies
      run: |
        go mod download

    - name: Build
      run: make build

    - name: Lint and Test
      run: |
        make install-dev-tools
        make lint
        make test
