// Code generated by go-swagger; DO NOT EDIT.

package context

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	ccontext "context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPostContextsEditPhpParams creates a new PostContextsEditPhpParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostContextsEditPhpParams() *PostContextsEditPhpParams {
	return &PostContextsEditPhpParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostContextsEditPhpParamsWithTimeout creates a new PostContextsEditPhpParams object
// with the ability to set a timeout on a request.
func NewPostContextsEditPhpParamsWithTimeout(timeout time.Duration) *PostContextsEditPhpParams {
	return &PostContextsEditPhpParams{
		timeout: timeout,
	}
}

// NewPostContextsEditPhpParamsWithContext creates a new PostContextsEditPhpParams object
// with the ability to set a context for a request.
func NewPostContextsEditPhpParamsWithContext(ctx ccontext.Context) *PostContextsEditPhpParams {
	return &PostContextsEditPhpParams{
		Context: ctx,
	}
}

// NewPostContextsEditPhpParamsWithHTTPClient creates a new PostContextsEditPhpParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostContextsEditPhpParamsWithHTTPClient(client *http.Client) *PostContextsEditPhpParams {
	return &PostContextsEditPhpParams{
		HTTPClient: client,
	}
}

/* PostContextsEditPhpParams contains all the parameters to send to the API endpoint
   for the post contexts edit php operation.

   Typically these are written to a http.Request.
*/
type PostContextsEditPhpParams struct {

	// ID.
	ID string

	// Name.
	Name *string

	// Private.
	Private *int64

	timeout    time.Duration
	Context    ccontext.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post contexts edit php params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostContextsEditPhpParams) WithDefaults() *PostContextsEditPhpParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post contexts edit php params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostContextsEditPhpParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post contexts edit php params
func (o *PostContextsEditPhpParams) WithTimeout(timeout time.Duration) *PostContextsEditPhpParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post contexts edit php params
func (o *PostContextsEditPhpParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post contexts edit php params
func (o *PostContextsEditPhpParams) WithContext(ctx ccontext.Context) *PostContextsEditPhpParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post contexts edit php params
func (o *PostContextsEditPhpParams) SetContext(ctx ccontext.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post contexts edit php params
func (o *PostContextsEditPhpParams) WithHTTPClient(client *http.Client) *PostContextsEditPhpParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post contexts edit php params
func (o *PostContextsEditPhpParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the post contexts edit php params
func (o *PostContextsEditPhpParams) WithID(id string) *PostContextsEditPhpParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post contexts edit php params
func (o *PostContextsEditPhpParams) SetID(id string) {
	o.ID = id
}

// WithName adds the name to the post contexts edit php params
func (o *PostContextsEditPhpParams) WithName(name *string) *PostContextsEditPhpParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the post contexts edit php params
func (o *PostContextsEditPhpParams) SetName(name *string) {
	o.Name = name
}

// WithPrivate adds the private to the post contexts edit php params
func (o *PostContextsEditPhpParams) WithPrivate(private *int64) *PostContextsEditPhpParams {
	o.SetPrivate(private)
	return o
}

// SetPrivate adds the private to the post contexts edit php params
func (o *PostContextsEditPhpParams) SetPrivate(private *int64) {
	o.Private = private
}

// WriteToRequest writes these params to a swagger request
func (o *PostContextsEditPhpParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param id
	qrID := o.ID
	qID := qrID
	if qID != "" {

		if err := r.SetQueryParam("id", qID); err != nil {
			return err
		}
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if o.Private != nil {

		// query param private
		var qrPrivate int64

		if o.Private != nil {
			qrPrivate = *o.Private
		}
		qPrivate := swag.FormatInt64(qrPrivate)
		if qPrivate != "" {

			if err := r.SetQueryParam("private", qPrivate); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
