// Code generated by go-swagger; DO NOT EDIT.

package context

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	ccontext "context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetContextsGetPhpParams creates a new GetContextsGetPhpParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetContextsGetPhpParams() *GetContextsGetPhpParams {
	return &GetContextsGetPhpParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetContextsGetPhpParamsWithTimeout creates a new GetContextsGetPhpParams object
// with the ability to set a timeout on a request.
func NewGetContextsGetPhpParamsWithTimeout(timeout time.Duration) *GetContextsGetPhpParams {
	return &GetContextsGetPhpParams{
		timeout: timeout,
	}
}

// NewGetContextsGetPhpParamsWithContext creates a new GetContextsGetPhpParams object
// with the ability to set a context for a request.
func NewGetContextsGetPhpParamsWithContext(ctx ccontext.Context) *GetContextsGetPhpParams {
	return &GetContextsGetPhpParams{
		Context: ctx,
	}
}

// NewGetContextsGetPhpParamsWithHTTPClient creates a new GetContextsGetPhpParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetContextsGetPhpParamsWithHTTPClient(client *http.Client) *GetContextsGetPhpParams {
	return &GetContextsGetPhpParams{
		HTTPClient: client,
	}
}

/*
GetContextsGetPhpParams contains all the parameters to send to the API endpoint

	for the get contexts get php operation.

	Typically these are written to a http.Request.
*/
type GetContextsGetPhpParams struct {
	timeout    time.Duration
	Context    ccontext.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get contexts get php params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetContextsGetPhpParams) WithDefaults() *GetContextsGetPhpParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get contexts get php params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetContextsGetPhpParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get contexts get php params
func (o *GetContextsGetPhpParams) WithTimeout(timeout time.Duration) *GetContextsGetPhpParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get contexts get php params
func (o *GetContextsGetPhpParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get contexts get php params
func (o *GetContextsGetPhpParams) WithContext(ctx ccontext.Context) *GetContextsGetPhpParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get contexts get php params
func (o *GetContextsGetPhpParams) SetContext(ctx ccontext.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get contexts get php params
func (o *GetContextsGetPhpParams) WithHTTPClient(client *http.Client) *GetContextsGetPhpParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get contexts get php params
func (o *GetContextsGetPhpParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetContextsGetPhpParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
