// Code generated by go-swagger; DO NOT EDIT.

package context

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new context API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for context API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetContextsGetPhp(params *GetContextsGetPhpParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetContextsGetPhpOK, error)

	PostContextsAddPhp(params *PostContextsAddPhpParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostContextsAddPhpOK, error)

	PostContextsDeletePhp(params *PostContextsDeletePhpParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostContextsDeletePhpOK, error)

	PostContextsEditPhp(params *PostContextsEditPhpParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostContextsEditPhpOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetContextsGetPhp get contexts get php API
*/
func (a *Client) GetContextsGetPhp(params *GetContextsGetPhpParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetContextsGetPhpOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetContextsGetPhpParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetContextsGetPhp",
		Method:             "GET",
		PathPattern:        "/contexts/get.php",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetContextsGetPhpReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetContextsGetPhpOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetContextsGetPhp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostContextsAddPhp post contexts add php API
*/
func (a *Client) PostContextsAddPhp(params *PostContextsAddPhpParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostContextsAddPhpOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostContextsAddPhpParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostContextsAddPhp",
		Method:             "POST",
		PathPattern:        "/contexts/add.php",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostContextsAddPhpReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostContextsAddPhpOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostContextsAddPhp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostContextsDeletePhp post contexts delete php API
*/
func (a *Client) PostContextsDeletePhp(params *PostContextsDeletePhpParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostContextsDeletePhpOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostContextsDeletePhpParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostContextsDeletePhp",
		Method:             "POST",
		PathPattern:        "/contexts/delete.php",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostContextsDeletePhpReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostContextsDeletePhpOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostContextsDeletePhp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostContextsEditPhp post contexts edit php API
*/
func (a *Client) PostContextsEditPhp(params *PostContextsEditPhpParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostContextsEditPhpOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostContextsEditPhpParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostContextsEditPhp",
		Method:             "POST",
		PathPattern:        "/contexts/edit.php",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostContextsEditPhpReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostContextsEditPhpOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostContextsEditPhp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
